name: T3SL4TNT
author: [SYN_T3SL4, BatuAdam, Sayç, Civciv]
version: 04.10.2022
main: me.t3sl4.tnt.T3SL4TNT
website: github.com/hidirektor

commands:
  patlayici:
    description: Main command of T3SL4TNT!
    aliases: [batuadam]
